// type for errors
export const GET_ERRORS = 'GET_ERRORS';
// types for category actions
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
// types for blog actions
export const GET_BLOGS = 'GET_BLOGS';
export const GET_BLOG = 'GET_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';
// types for tag actions
export const GET_TAGS = 'GET_TAGS';
export const GET_TAG = 'GET_TAG';
// types for post actions
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const DELETE_POST = 'DELETE_POST';
// types for security actions
export const SET_CURRENT_USER = "SET_CURRENT_USER"
